# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "nokogiri", ">=1.5.9"
gem "crass", "~>1.0.2"

gem "rake", ">=0.8", :group => [:development, :test]
gem "minitest", "~>2.2", :group => [:development, :test]
gem "rr", "~>1.2.0", :group => [:development, :test]
gem "json", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "hoe-debugging", ">=0", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "hoe-git", ">=0", :group => [:development, :test]
gem "concourse", ">=0.15.0", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]

# vim: syntax=ruby
