# frozen_string_literal: true

module Vite
  # We use two manifest files to list the assets loaded in our backend:
  # - manifest.json: This is the main file that lists all the javascript and stylesheets our frontend app uses
  # - manifest-assets.json: This only lists media assets linked directly from our backend, mainly images
  #
  # Not all the assets listed in the manifest.json file are linked or used by the app view, so we don't need to
  # keep track of those. The idea behind this class is to keep track only of the main entrypoints and all their
  # subsequent imports. Imports in this case include other javascript modules and stylesheets generated by Vite.
  #
  # This class focuses on reducing the amount of data we keep per entrypoint and making fast lookups. To do so
  # it keeps two main datastructures:
  # - entries: A Hash with references to each main entrypoint (including media assets)
  # - pool: An Array with all the referenced imports and stylesheets
  #
  # Each entrypoint has a list of IDs for each import and stylesheet that it needs to load, this ID is
  # an index to the main pool. With this the referenced asset is stored only once and referenced across
  # entries with a unique ID. In the original manifest files references are also nested, if an entrypoint
  # imports a javascript module, this first module can import other modules and stylesheet and so on. To keep
  # fetching entrypoints fast, the final list of modules and stylesheets to load per entrypoint
  # is expanded when loading the manifest data and not when rendering views. Each entrypoint has the final
  # list of IDs of imports and stylesheets it will need to link in the backend, without further recursive
  # checks.
  class Manifest
    class Entry
      attr_reader :file, :integrity
      attr_accessor :import_ids, :stylesheet_ids, :pool

      def self.from_json(raw)
        new(file: raw['file'], integrity: raw['integrity'], name: raw['name'])
      end

      def initialize(file:, integrity:, name: '', import_ids: [], stylesheet_ids: [], pool: [])
        @file = file
        @integrity = integrity
        @name = name
        @import_ids = import_ids
        @stylesheet_ids = stylesheet_ids
        @pool = pool
      end

      def imports
        find_entries(@import_ids)
      end

      def stylesheets
        find_entries(@stylesheet_ids)
      end

      private

      def find_entries(ids)
        ids.filter_map { |id| @pool[id] }
      end
    end

    attr_reader :config, :entries, :pool

    def initialize(config:)
      @config = config
      @virtual = {}
      @entries = {}
      @pool = []
      @loaded = false
    end

    def reload
      @loaded = false
      load
    end

    # TODO: Error handling
    def load
      return if @loaded

      @virtual = {}
      @entries = {}
      @pool = []

      json = JSON.load_file(config.manifest_path)
      json.each do |key, raw|
        # Only select main entrypoints and locales
        next unless raw['isEntry'] || key.start_with?('mastodon/locales/')

        import_ids, stylesheet_ids = resolve_relations(json, raw)

        @virtual[raw['name']] = key
        @entries[key] = Entry.from_json(raw).tap do |entry|
          entry.import_ids = import_ids
          entry.stylesheet_ids = stylesheet_ids
          entry.pool = @pool
        end
      end

      assets = JSON.load_file(config.manifest_assets_path)
      assets.each do |key, raw|
        @entries[key] = Entry.from_json(raw)
      end

      @loaded = true
    end

    # TODO: Errors?
    def fetch(name, type: nil)
      name = @virtual[name] if type == :virtual
      entries[name]
    end

    private

    def resolve_relations(manifest, raw)
      # NOTE: By using Set we make sure we add each asset only once
      imports = Set.new
      stylesheets = Set.new

      (raw['imports'] || []).each do |import|
        raw = manifest[import]
        next unless raw

        id = find_or_create_entry(Entry.from_json(raw))
        subimports, substyles = resolve_relations(manifest, raw)

        subimports.each { |sub| imports.add sub }
        substyles.each { |sub| stylesheets.add sub }
        imports.add id
      end

      (raw['css'] || []).each do |stylesheet|
        # the css field includes the file names of the stylesheets and not
        # the src names which are the ones used as keys in the manifest
        raw = manifest.values.find { |value| value['file'] == stylesheet }
        next unless raw

        id = find_or_create_entry(Entry.from_json(raw))
        stylesheets.add id
        subimports, substyles = resolve_relations(manifest, raw)

        subimports.each { |sub| imports.add sub }
        substyles.each { |sub| stylesheets.add sub }
      end

      [imports, stylesheets].map(&:to_a)
    end

    def find_or_create_entry(entry)
      id = @pool.find_index { |record| record.file == entry.file }
      if id.nil?
        @pool << entry
        id = @pool.size - 1 # last ID
      end

      id
    end
  end
end
