 comment: false # Do not leave PR comments
coverage:
  status:
    project:
      default:
        informational: true # GitHub status check is not blocking
    patch:
      default:
        informational: true # GitHub status check is not blocking
github_checks:
  annotations: false # Disable Codecov annotations
