daysUntilStale: 120
daysUntilClose: 7
exemptLabels:
  - security
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
only: pulls
