exclude:
  - 'vendor/**/*'

require:
  - ./lib/linter/haml_middle_dot.rb

linters:
  AltText:
    enabled: true
  MiddleDot:
    enabled: true
  LineLength:
    max: 256 # Override default of 80
  ViewLength:
    max: 128 # Override default of 100
