exclude:
  - 'vendor/**/*'

require:
  - ./lib/linter/haml_middle_dot.rb

linters:
  AltText:
    enabled: true
  MiddleDot:
    enabled: true
  LineLength:
    max: 300
  ViewLength:
    max: 200 # Override default value of 100 inherited from rubocop
