exclude:
  - 'vendor/**/*'

require:
  - ./lib/linter/haml_middle_dot.rb

linters:
  AltText:
    enabled: true
  MiddleDot:
    enabled: true
  LineLength:
    max: 256 # Override default value of 80 inherited from rubocop
  ViewLength:
    max: 128 # Override default value of 100 inherited from rubocop
