---
AllCops:
  CacheRootDirectory: tmp
  DisplayStyleGuide: true
  Exclude:
    - Vagrantfile
    - config/initializers/json_ld*
    - lib/mastodon/migration_helpers.rb
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2 # Oldest supported ruby version

inherit_from:
  - .rubocop/layout.yml
  - .rubocop/rails.yml
  - .rubocop/rspec_rails.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml
  - .rubocop/custom.yml
  - .rubocop_todo.yml
  - .rubocop/strict.yml

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-performance
  - standard-rails
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara
