FROM node:8.11-stretch as node
FROM ruby:2.5

LABEL maintainer="https://github.com/tri-star/mastodon" \
      description="A GNU Social-compatible microblogging server"

ARG UID=991
ARG GID=991

ENV PATH=/mastodon/bin:/usr/local/bin:$PATH \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_ENV=production \
    NODE_ENV=production

ARG YARN_VERSION=1.3.2
ARG YARN_DOWNLOAD_SHA256=6cfe82e530ef0837212f13e45c1565ba53f5199eec2527b85ecbcd88bf26821d
ARG LIBICONV_VERSION=1.15
ARG LIBICONV_DOWNLOAD_SHA256=ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178

EXPOSE 3000 4000 8080

WORKDIR /mastodon

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/npm /usr/local/bin/npm
COPY --from=node /opt/yarn-* /opt/yarn

RUN apt update \
 && apt install -y build-essential \
    libicu-dev \
    libidn11-dev \
    libssl-dev \
    libtool \
    libtool-bin \
    pkg-config \
    gcc \
    autoconf \
    bison \
    libpq-dev \
    libprotobuf-dev \
    python \
    git \
    curl \
 && apt install -y \
    libjemalloc1 \
    ca-certificates \
    ffmpeg \
    file \
    git \
    imagemagick \
    libpq5 \
    protobuf-compiler \
    tzdata \
 && update-ca-certificates \
 && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
 && ln -s /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg \
 && mkdir -p /tmp/src /opt \
 && wget -O libiconv.tar.gz "https://ftp.gnu.org/pub/gnu/libiconv/libiconv-$LIBICONV_VERSION.tar.gz" \
 && echo "$LIBICONV_DOWNLOAD_SHA256 *libiconv.tar.gz" | sha256sum -c - \
 && tar -xzf libiconv.tar.gz -C /tmp/src \
 && rm libiconv.tar.gz \
 && cd /tmp/src/libiconv-$LIBICONV_VERSION \
 && ./configure --prefix=/usr/local \
 && make -j$(getconf _NPROCESSORS_ONLN)\
 && make install \
 && libtool --finish /usr/local/lib \
 && cd /mastodon \
 && rm -rf /tmp/* \
 && apt clean

COPY Gemfile Gemfile.lock package.json yarn.lock .yarnclean /mastodon/

RUN bundle config build.nokogiri --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include \
 && bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without test development \
 && yarn --pure-lockfile \
 && yarn cache clean

RUN addgroup --gid ${GID} mastodon && useradd -b /mastodon -s /bin/sh -g ${GID} -u ${UID} mastodon \
 && mkdir -p /mastodon/public/system /mastodon/public/assets /mastodon/public/packs /mastodon/build /mastodon/mastodon \
 && chown -R mastodon:mastodon /mastodon/public /mastodon/mastodon

COPY . /mastodon

RUN chown -R mastodon:mastodon tmp build
RUN chmod +x /mastodon/boot.sh

VOLUME /mastodon/public/system

USER mastodon

RUN OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder bundle exec rails assets:precompile

USER root
