name: 'Setup Ruby'
description: 'Setup a Ruby environment ready to run the Mastodon code'
inputs:
  ruby-version:
    description: The Ruby version to install
    default: '.ruby-version'
  additional-system-dependencies:
    description: 'Additional packages to install'

runs:
  using: 'composite'
  steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Change APT cache ownership
      run: sudo chown -R $USER /var/cache/apt
      shell: bash

    - name: Cache APT Packages
      id: cache-apt-packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ steps.date.outputs.date }}
        restore-keys: |
          ${{ runner.os }}-apt-${{ steps.date.outputs.date }}

    - name: Install system dependencies
      if: steps.cache-apt-packages.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          libicu-dev \
          libidn11-dev \
          libvips42 \
          libheif-plugin-aomdec \
          libheif-plugin-libde265 \
          ${{ inputs.additional-system-dependencies }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
