name: 'Setup Ruby'
description: 'Setup a Ruby environment ready to run the Mastodon code'
inputs:
  ruby-version:
    description: The Ruby version to install
    default: '.ruby-version'
  additional-system-dependencies:
    description: 'Additional packages to install'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
          libicu-dev \
          libidn11-dev \
          libvips42 \
          libheif-plugin-aomdec \
          libheif-plugin-libde265 \
          ${{ inputs.additional-system-dependencies }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
