# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "mini_portile2", "~>2.3.0"

gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-debugging", "~>1.4", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "minitest", "~>5.8.4", :group => [:development, :test]
gem "rake", "~>12.0", :group => [:development, :test]
gem "rake-compiler", "~>1.0.3", :group => [:development, :test]
gem "rake-compiler-dock", "~>0.6.2", :group => [:development, :test]
gem "racc", "~>1.4.14", :group => [:development, :test], :platform => [:ruby, :mingw, :x64_mingw]
gem "rexical", "~>1.0.5", :group => [:development, :test], :platform => [:ruby, :mingw, :x64_mingw]
gem "concourse", "~>0.15", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe", "~>3.16", :group => [:development, :test]

# vim: syntax=ruby
