name: Deployment troubleshooting
description: |
  You are a server administrator and you are encountering a technical issue during installation, upgrade or operations of Mastodon.
labels: ['status/to triage']
type: 'Troubleshooting'
body:
  - type: markdown
    attributes:
      value: |
        Make sure that you are submitting a new bug that was not previously reported or already fixed.

        Please use a concise and distinct title for the issue.
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: What were you trying to do?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: Expected behaviour
      description: What should have happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Actual behaviour
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed description
    validations:
      required: false
  - type: input
    attributes:
      label: Mastodon instance
      description: The address of the Mastodon instance where you experienced the issue
      placeholder: mastodon.social
    validations:
      required: true
  - type: input
    attributes:
      label: Mastodon version
      description: |
        This is displayed at the bottom of the About page, eg. `v4.4.0-alpha.1`
      placeholder: v4.3.0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Details about your environment, like how Mastodon is deployed, if containers are used, version numbers, etc.
      value: |
        Please at least include those informations:
        - Operating system: (eg. Ubuntu 22.04)
        - Ruby version: (from `ruby --version`, eg. v3.3.5)
        - Node.js version: (from `node --version`, eg. v20.18.0)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Technical details
      description: |
        Any additional technical details you may have, like logs or error traces
    validations:
      required: false
