Metrics/LineLength:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed

Style/FormatString:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes
