// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_spec.proto

#ifndef PROTOBUF_task_5fspec_2eproto__INCLUDED
#define PROTOBUF_task_5fspec_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace chrome_lang_id {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_task_5fspec_2eproto();
void protobuf_AssignDesc_task_5fspec_2eproto();
void protobuf_ShutdownFile_task_5fspec_2eproto();

class TaskInput;
class TaskInput_Part;
class TaskOutput;
class TaskSpec;
class TaskSpec_Parameter;

// ===================================================================

class TaskInput_Part : public ::google::protobuf::MessageLite {
 public:
  TaskInput_Part();
  virtual ~TaskInput_Part();

  TaskInput_Part(const TaskInput_Part& from);

  inline TaskInput_Part& operator=(const TaskInput_Part& from) {
    CopyFrom(from);
    return *this;
  }

  static const TaskInput_Part& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const TaskInput_Part* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(TaskInput_Part* other);

  // implements Message ----------------------------------------------

  TaskInput_Part* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const TaskInput_Part& from);
  void MergeFrom(const TaskInput_Part& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string file_pattern = 7;
  inline bool has_file_pattern() const;
  inline void clear_file_pattern();
  static const int kFilePatternFieldNumber = 7;
  inline const ::std::string& file_pattern() const;
  inline void set_file_pattern(const ::std::string& value);
  inline void set_file_pattern(const char* value);
  inline void set_file_pattern(const char* value, size_t size);
  inline ::std::string* mutable_file_pattern();
  inline ::std::string* release_file_pattern();
  inline void set_allocated_file_pattern(::std::string* file_pattern);

  // optional string file_format = 8;
  inline bool has_file_format() const;
  inline void clear_file_format();
  static const int kFileFormatFieldNumber = 8;
  inline const ::std::string& file_format() const;
  inline void set_file_format(const ::std::string& value);
  inline void set_file_format(const char* value);
  inline void set_file_format(const char* value, size_t size);
  inline ::std::string* mutable_file_format();
  inline ::std::string* release_file_format();
  inline void set_allocated_file_format(::std::string* file_format);

  // optional string record_format = 9;
  inline bool has_record_format() const;
  inline void clear_record_format();
  static const int kRecordFormatFieldNumber = 9;
  inline const ::std::string& record_format() const;
  inline void set_record_format(const ::std::string& value);
  inline void set_record_format(const char* value);
  inline void set_record_format(const char* value, size_t size);
  inline ::std::string* mutable_record_format();
  inline ::std::string* release_record_format();
  inline void set_allocated_record_format(::std::string* record_format);

  // @@protoc_insertion_point(class_scope:chrome_lang_id.TaskInput.Part)
 private:
  inline void set_has_file_pattern();
  inline void clear_has_file_pattern();
  inline void set_has_file_format();
  inline void clear_has_file_format();
  inline void set_has_record_format();
  inline void clear_has_record_format();

  ::std::string* file_pattern_;
  ::std::string* file_format_;
  ::std::string* record_format_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_task_5fspec_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_task_5fspec_2eproto();
  #endif
  friend void protobuf_AssignDesc_task_5fspec_2eproto();
  friend void protobuf_ShutdownFile_task_5fspec_2eproto();

  void InitAsDefaultInstance();
  static TaskInput_Part* default_instance_;
};
// -------------------------------------------------------------------

class TaskInput : public ::google::protobuf::MessageLite {
 public:
  TaskInput();
  virtual ~TaskInput();

  TaskInput(const TaskInput& from);

  inline TaskInput& operator=(const TaskInput& from) {
    CopyFrom(from);
    return *this;
  }

  static const TaskInput& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const TaskInput* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(TaskInput* other);

  // implements Message ----------------------------------------------

  TaskInput* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const TaskInput& from);
  void MergeFrom(const TaskInput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef TaskInput_Part Part;

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string creator = 2;
  inline bool has_creator() const;
  inline void clear_creator();
  static const int kCreatorFieldNumber = 2;
  inline const ::std::string& creator() const;
  inline void set_creator(const ::std::string& value);
  inline void set_creator(const char* value);
  inline void set_creator(const char* value, size_t size);
  inline ::std::string* mutable_creator();
  inline ::std::string* release_creator();
  inline void set_allocated_creator(::std::string* creator);

  // repeated string file_format = 3;
  inline int file_format_size() const;
  inline void clear_file_format();
  static const int kFileFormatFieldNumber = 3;
  inline const ::std::string& file_format(int index) const;
  inline ::std::string* mutable_file_format(int index);
  inline void set_file_format(int index, const ::std::string& value);
  inline void set_file_format(int index, const char* value);
  inline void set_file_format(int index, const char* value, size_t size);
  inline ::std::string* add_file_format();
  inline void add_file_format(const ::std::string& value);
  inline void add_file_format(const char* value);
  inline void add_file_format(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& file_format() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_file_format();

  // repeated string record_format = 4;
  inline int record_format_size() const;
  inline void clear_record_format();
  static const int kRecordFormatFieldNumber = 4;
  inline const ::std::string& record_format(int index) const;
  inline ::std::string* mutable_record_format(int index);
  inline void set_record_format(int index, const ::std::string& value);
  inline void set_record_format(int index, const char* value);
  inline void set_record_format(int index, const char* value, size_t size);
  inline ::std::string* add_record_format();
  inline void add_record_format(const ::std::string& value);
  inline void add_record_format(const char* value);
  inline void add_record_format(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& record_format() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_record_format();

  // optional bool multi_file = 5 [default = false];
  inline bool has_multi_file() const;
  inline void clear_multi_file();
  static const int kMultiFileFieldNumber = 5;
  inline bool multi_file() const;
  inline void set_multi_file(bool value);

  // repeated group Part = 6 {
  inline int part_size() const;
  inline void clear_part();
  static const int kPartFieldNumber = 6;
  inline const ::chrome_lang_id::TaskInput_Part& part(int index) const;
  inline ::chrome_lang_id::TaskInput_Part* mutable_part(int index);
  inline ::chrome_lang_id::TaskInput_Part* add_part();
  inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput_Part >&
      part() const;
  inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput_Part >*
      mutable_part();

  // @@protoc_insertion_point(class_scope:chrome_lang_id.TaskInput)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_creator();
  inline void clear_has_creator();
  inline void set_has_multi_file();
  inline void clear_has_multi_file();

  ::std::string* name_;
  ::std::string* creator_;
  ::google::protobuf::RepeatedPtrField< ::std::string> file_format_;
  ::google::protobuf::RepeatedPtrField< ::std::string> record_format_;
  ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput_Part > part_;
  bool multi_file_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_task_5fspec_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_task_5fspec_2eproto();
  #endif
  friend void protobuf_AssignDesc_task_5fspec_2eproto();
  friend void protobuf_ShutdownFile_task_5fspec_2eproto();

  void InitAsDefaultInstance();
  static TaskInput* default_instance_;
};
// -------------------------------------------------------------------

class TaskOutput : public ::google::protobuf::MessageLite {
 public:
  TaskOutput();
  virtual ~TaskOutput();

  TaskOutput(const TaskOutput& from);

  inline TaskOutput& operator=(const TaskOutput& from) {
    CopyFrom(from);
    return *this;
  }

  static const TaskOutput& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const TaskOutput* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(TaskOutput* other);

  // implements Message ----------------------------------------------

  TaskOutput* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const TaskOutput& from);
  void MergeFrom(const TaskOutput& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string file_format = 2;
  inline bool has_file_format() const;
  inline void clear_file_format();
  static const int kFileFormatFieldNumber = 2;
  inline const ::std::string& file_format() const;
  inline void set_file_format(const ::std::string& value);
  inline void set_file_format(const char* value);
  inline void set_file_format(const char* value, size_t size);
  inline ::std::string* mutable_file_format();
  inline ::std::string* release_file_format();
  inline void set_allocated_file_format(::std::string* file_format);

  // optional string record_format = 3;
  inline bool has_record_format() const;
  inline void clear_record_format();
  static const int kRecordFormatFieldNumber = 3;
  inline const ::std::string& record_format() const;
  inline void set_record_format(const ::std::string& value);
  inline void set_record_format(const char* value);
  inline void set_record_format(const char* value, size_t size);
  inline ::std::string* mutable_record_format();
  inline ::std::string* release_record_format();
  inline void set_allocated_record_format(::std::string* record_format);

  // optional int32 shards = 4 [default = 0];
  inline bool has_shards() const;
  inline void clear_shards();
  static const int kShardsFieldNumber = 4;
  inline ::google::protobuf::int32 shards() const;
  inline void set_shards(::google::protobuf::int32 value);

  // optional string file_base = 5;
  inline bool has_file_base() const;
  inline void clear_file_base();
  static const int kFileBaseFieldNumber = 5;
  inline const ::std::string& file_base() const;
  inline void set_file_base(const ::std::string& value);
  inline void set_file_base(const char* value);
  inline void set_file_base(const char* value, size_t size);
  inline ::std::string* mutable_file_base();
  inline ::std::string* release_file_base();
  inline void set_allocated_file_base(::std::string* file_base);

  // optional string file_extension = 6;
  inline bool has_file_extension() const;
  inline void clear_file_extension();
  static const int kFileExtensionFieldNumber = 6;
  inline const ::std::string& file_extension() const;
  inline void set_file_extension(const ::std::string& value);
  inline void set_file_extension(const char* value);
  inline void set_file_extension(const char* value, size_t size);
  inline ::std::string* mutable_file_extension();
  inline ::std::string* release_file_extension();
  inline void set_allocated_file_extension(::std::string* file_extension);

  // @@protoc_insertion_point(class_scope:chrome_lang_id.TaskOutput)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_file_format();
  inline void clear_has_file_format();
  inline void set_has_record_format();
  inline void clear_has_record_format();
  inline void set_has_shards();
  inline void clear_has_shards();
  inline void set_has_file_base();
  inline void clear_has_file_base();
  inline void set_has_file_extension();
  inline void clear_has_file_extension();

  ::std::string* name_;
  ::std::string* file_format_;
  ::std::string* record_format_;
  ::std::string* file_base_;
  ::std::string* file_extension_;
  ::google::protobuf::int32 shards_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_task_5fspec_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_task_5fspec_2eproto();
  #endif
  friend void protobuf_AssignDesc_task_5fspec_2eproto();
  friend void protobuf_ShutdownFile_task_5fspec_2eproto();

  void InitAsDefaultInstance();
  static TaskOutput* default_instance_;
};
// -------------------------------------------------------------------

class TaskSpec_Parameter : public ::google::protobuf::MessageLite {
 public:
  TaskSpec_Parameter();
  virtual ~TaskSpec_Parameter();

  TaskSpec_Parameter(const TaskSpec_Parameter& from);

  inline TaskSpec_Parameter& operator=(const TaskSpec_Parameter& from) {
    CopyFrom(from);
    return *this;
  }

  static const TaskSpec_Parameter& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const TaskSpec_Parameter* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(TaskSpec_Parameter* other);

  // implements Message ----------------------------------------------

  TaskSpec_Parameter* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const TaskSpec_Parameter& from);
  void MergeFrom(const TaskSpec_Parameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 4;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 4;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string value = 5;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 5;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:chrome_lang_id.TaskSpec.Parameter)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_value();
  inline void clear_has_value();

  ::std::string* name_;
  ::std::string* value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_task_5fspec_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_task_5fspec_2eproto();
  #endif
  friend void protobuf_AssignDesc_task_5fspec_2eproto();
  friend void protobuf_ShutdownFile_task_5fspec_2eproto();

  void InitAsDefaultInstance();
  static TaskSpec_Parameter* default_instance_;
};
// -------------------------------------------------------------------

class TaskSpec : public ::google::protobuf::MessageLite {
 public:
  TaskSpec();
  virtual ~TaskSpec();

  TaskSpec(const TaskSpec& from);

  inline TaskSpec& operator=(const TaskSpec& from) {
    CopyFrom(from);
    return *this;
  }

  static const TaskSpec& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const TaskSpec* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(TaskSpec* other);

  // implements Message ----------------------------------------------

  TaskSpec* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const TaskSpec& from);
  void MergeFrom(const TaskSpec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef TaskSpec_Parameter Parameter;

  // accessors -------------------------------------------------------

  // optional string task_name = 1;
  inline bool has_task_name() const;
  inline void clear_task_name();
  static const int kTaskNameFieldNumber = 1;
  inline const ::std::string& task_name() const;
  inline void set_task_name(const ::std::string& value);
  inline void set_task_name(const char* value);
  inline void set_task_name(const char* value, size_t size);
  inline ::std::string* mutable_task_name();
  inline ::std::string* release_task_name();
  inline void set_allocated_task_name(::std::string* task_name);

  // optional string task_type = 2;
  inline bool has_task_type() const;
  inline void clear_task_type();
  static const int kTaskTypeFieldNumber = 2;
  inline const ::std::string& task_type() const;
  inline void set_task_type(const ::std::string& value);
  inline void set_task_type(const char* value);
  inline void set_task_type(const char* value, size_t size);
  inline ::std::string* mutable_task_type();
  inline ::std::string* release_task_type();
  inline void set_allocated_task_type(::std::string* task_type);

  // repeated group Parameter = 3 {
  inline int parameter_size() const;
  inline void clear_parameter();
  static const int kParameterFieldNumber = 3;
  inline const ::chrome_lang_id::TaskSpec_Parameter& parameter(int index) const;
  inline ::chrome_lang_id::TaskSpec_Parameter* mutable_parameter(int index);
  inline ::chrome_lang_id::TaskSpec_Parameter* add_parameter();
  inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskSpec_Parameter >&
      parameter() const;
  inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskSpec_Parameter >*
      mutable_parameter();

  // repeated .chrome_lang_id.TaskInput input = 6;
  inline int input_size() const;
  inline void clear_input();
  static const int kInputFieldNumber = 6;
  inline const ::chrome_lang_id::TaskInput& input(int index) const;
  inline ::chrome_lang_id::TaskInput* mutable_input(int index);
  inline ::chrome_lang_id::TaskInput* add_input();
  inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput >&
      input() const;
  inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput >*
      mutable_input();

  // repeated .chrome_lang_id.TaskOutput output = 7;
  inline int output_size() const;
  inline void clear_output();
  static const int kOutputFieldNumber = 7;
  inline const ::chrome_lang_id::TaskOutput& output(int index) const;
  inline ::chrome_lang_id::TaskOutput* mutable_output(int index);
  inline ::chrome_lang_id::TaskOutput* add_output();
  inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskOutput >&
      output() const;
  inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskOutput >*
      mutable_output();

  // @@protoc_insertion_point(class_scope:chrome_lang_id.TaskSpec)
 private:
  inline void set_has_task_name();
  inline void clear_has_task_name();
  inline void set_has_task_type();
  inline void clear_has_task_type();

  ::std::string* task_name_;
  ::std::string* task_type_;
  ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskSpec_Parameter > parameter_;
  ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput > input_;
  ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskOutput > output_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_task_5fspec_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_task_5fspec_2eproto();
  #endif
  friend void protobuf_AssignDesc_task_5fspec_2eproto();
  friend void protobuf_ShutdownFile_task_5fspec_2eproto();

  void InitAsDefaultInstance();
  static TaskSpec* default_instance_;
};
// ===================================================================


// ===================================================================

// TaskInput_Part

// optional string file_pattern = 7;
inline bool TaskInput_Part::has_file_pattern() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskInput_Part::set_has_file_pattern() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskInput_Part::clear_has_file_pattern() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskInput_Part::clear_file_pattern() {
  if (file_pattern_ != &::google::protobuf::internal::kEmptyString) {
    file_pattern_->clear();
  }
  clear_has_file_pattern();
}
inline const ::std::string& TaskInput_Part::file_pattern() const {
  return *file_pattern_;
}
inline void TaskInput_Part::set_file_pattern(const ::std::string& value) {
  set_has_file_pattern();
  if (file_pattern_ == &::google::protobuf::internal::kEmptyString) {
    file_pattern_ = new ::std::string;
  }
  file_pattern_->assign(value);
}
inline void TaskInput_Part::set_file_pattern(const char* value) {
  set_has_file_pattern();
  if (file_pattern_ == &::google::protobuf::internal::kEmptyString) {
    file_pattern_ = new ::std::string;
  }
  file_pattern_->assign(value);
}
inline void TaskInput_Part::set_file_pattern(const char* value, size_t size) {
  set_has_file_pattern();
  if (file_pattern_ == &::google::protobuf::internal::kEmptyString) {
    file_pattern_ = new ::std::string;
  }
  file_pattern_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput_Part::mutable_file_pattern() {
  set_has_file_pattern();
  if (file_pattern_ == &::google::protobuf::internal::kEmptyString) {
    file_pattern_ = new ::std::string;
  }
  return file_pattern_;
}
inline ::std::string* TaskInput_Part::release_file_pattern() {
  clear_has_file_pattern();
  if (file_pattern_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_pattern_;
    file_pattern_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskInput_Part::set_allocated_file_pattern(::std::string* file_pattern) {
  if (file_pattern_ != &::google::protobuf::internal::kEmptyString) {
    delete file_pattern_;
  }
  if (file_pattern) {
    set_has_file_pattern();
    file_pattern_ = file_pattern;
  } else {
    clear_has_file_pattern();
    file_pattern_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string file_format = 8;
inline bool TaskInput_Part::has_file_format() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskInput_Part::set_has_file_format() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskInput_Part::clear_has_file_format() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskInput_Part::clear_file_format() {
  if (file_format_ != &::google::protobuf::internal::kEmptyString) {
    file_format_->clear();
  }
  clear_has_file_format();
}
inline const ::std::string& TaskInput_Part::file_format() const {
  return *file_format_;
}
inline void TaskInput_Part::set_file_format(const ::std::string& value) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(value);
}
inline void TaskInput_Part::set_file_format(const char* value) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(value);
}
inline void TaskInput_Part::set_file_format(const char* value, size_t size) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput_Part::mutable_file_format() {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  return file_format_;
}
inline ::std::string* TaskInput_Part::release_file_format() {
  clear_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_format_;
    file_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskInput_Part::set_allocated_file_format(::std::string* file_format) {
  if (file_format_ != &::google::protobuf::internal::kEmptyString) {
    delete file_format_;
  }
  if (file_format) {
    set_has_file_format();
    file_format_ = file_format;
  } else {
    clear_has_file_format();
    file_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string record_format = 9;
inline bool TaskInput_Part::has_record_format() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TaskInput_Part::set_has_record_format() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TaskInput_Part::clear_has_record_format() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TaskInput_Part::clear_record_format() {
  if (record_format_ != &::google::protobuf::internal::kEmptyString) {
    record_format_->clear();
  }
  clear_has_record_format();
}
inline const ::std::string& TaskInput_Part::record_format() const {
  return *record_format_;
}
inline void TaskInput_Part::set_record_format(const ::std::string& value) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(value);
}
inline void TaskInput_Part::set_record_format(const char* value) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(value);
}
inline void TaskInput_Part::set_record_format(const char* value, size_t size) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput_Part::mutable_record_format() {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  return record_format_;
}
inline ::std::string* TaskInput_Part::release_record_format() {
  clear_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = record_format_;
    record_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskInput_Part::set_allocated_record_format(::std::string* record_format) {
  if (record_format_ != &::google::protobuf::internal::kEmptyString) {
    delete record_format_;
  }
  if (record_format) {
    set_has_record_format();
    record_format_ = record_format;
  } else {
    clear_has_record_format();
    record_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// TaskInput

// required string name = 1;
inline bool TaskInput::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskInput::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskInput::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskInput::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TaskInput::name() const {
  return *name_;
}
inline void TaskInput::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskInput::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskInput::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* TaskInput::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskInput::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string creator = 2;
inline bool TaskInput::has_creator() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskInput::set_has_creator() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskInput::clear_has_creator() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskInput::clear_creator() {
  if (creator_ != &::google::protobuf::internal::kEmptyString) {
    creator_->clear();
  }
  clear_has_creator();
}
inline const ::std::string& TaskInput::creator() const {
  return *creator_;
}
inline void TaskInput::set_creator(const ::std::string& value) {
  set_has_creator();
  if (creator_ == &::google::protobuf::internal::kEmptyString) {
    creator_ = new ::std::string;
  }
  creator_->assign(value);
}
inline void TaskInput::set_creator(const char* value) {
  set_has_creator();
  if (creator_ == &::google::protobuf::internal::kEmptyString) {
    creator_ = new ::std::string;
  }
  creator_->assign(value);
}
inline void TaskInput::set_creator(const char* value, size_t size) {
  set_has_creator();
  if (creator_ == &::google::protobuf::internal::kEmptyString) {
    creator_ = new ::std::string;
  }
  creator_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput::mutable_creator() {
  set_has_creator();
  if (creator_ == &::google::protobuf::internal::kEmptyString) {
    creator_ = new ::std::string;
  }
  return creator_;
}
inline ::std::string* TaskInput::release_creator() {
  clear_has_creator();
  if (creator_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = creator_;
    creator_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskInput::set_allocated_creator(::std::string* creator) {
  if (creator_ != &::google::protobuf::internal::kEmptyString) {
    delete creator_;
  }
  if (creator) {
    set_has_creator();
    creator_ = creator;
  } else {
    clear_has_creator();
    creator_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated string file_format = 3;
inline int TaskInput::file_format_size() const {
  return file_format_.size();
}
inline void TaskInput::clear_file_format() {
  file_format_.Clear();
}
inline const ::std::string& TaskInput::file_format(int index) const {
  return file_format_.Get(index);
}
inline ::std::string* TaskInput::mutable_file_format(int index) {
  return file_format_.Mutable(index);
}
inline void TaskInput::set_file_format(int index, const ::std::string& value) {
  file_format_.Mutable(index)->assign(value);
}
inline void TaskInput::set_file_format(int index, const char* value) {
  file_format_.Mutable(index)->assign(value);
}
inline void TaskInput::set_file_format(int index, const char* value, size_t size) {
  file_format_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput::add_file_format() {
  return file_format_.Add();
}
inline void TaskInput::add_file_format(const ::std::string& value) {
  file_format_.Add()->assign(value);
}
inline void TaskInput::add_file_format(const char* value) {
  file_format_.Add()->assign(value);
}
inline void TaskInput::add_file_format(const char* value, size_t size) {
  file_format_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TaskInput::file_format() const {
  return file_format_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TaskInput::mutable_file_format() {
  return &file_format_;
}

// repeated string record_format = 4;
inline int TaskInput::record_format_size() const {
  return record_format_.size();
}
inline void TaskInput::clear_record_format() {
  record_format_.Clear();
}
inline const ::std::string& TaskInput::record_format(int index) const {
  return record_format_.Get(index);
}
inline ::std::string* TaskInput::mutable_record_format(int index) {
  return record_format_.Mutable(index);
}
inline void TaskInput::set_record_format(int index, const ::std::string& value) {
  record_format_.Mutable(index)->assign(value);
}
inline void TaskInput::set_record_format(int index, const char* value) {
  record_format_.Mutable(index)->assign(value);
}
inline void TaskInput::set_record_format(int index, const char* value, size_t size) {
  record_format_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskInput::add_record_format() {
  return record_format_.Add();
}
inline void TaskInput::add_record_format(const ::std::string& value) {
  record_format_.Add()->assign(value);
}
inline void TaskInput::add_record_format(const char* value) {
  record_format_.Add()->assign(value);
}
inline void TaskInput::add_record_format(const char* value, size_t size) {
  record_format_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TaskInput::record_format() const {
  return record_format_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TaskInput::mutable_record_format() {
  return &record_format_;
}

// optional bool multi_file = 5 [default = false];
inline bool TaskInput::has_multi_file() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TaskInput::set_has_multi_file() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TaskInput::clear_has_multi_file() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TaskInput::clear_multi_file() {
  multi_file_ = false;
  clear_has_multi_file();
}
inline bool TaskInput::multi_file() const {
  return multi_file_;
}
inline void TaskInput::set_multi_file(bool value) {
  set_has_multi_file();
  multi_file_ = value;
}

// repeated group Part = 6 {
inline int TaskInput::part_size() const {
  return part_.size();
}
inline void TaskInput::clear_part() {
  part_.Clear();
}
inline const ::chrome_lang_id::TaskInput_Part& TaskInput::part(int index) const {
  return part_.Get(index);
}
inline ::chrome_lang_id::TaskInput_Part* TaskInput::mutable_part(int index) {
  return part_.Mutable(index);
}
inline ::chrome_lang_id::TaskInput_Part* TaskInput::add_part() {
  return part_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput_Part >&
TaskInput::part() const {
  return part_;
}
inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput_Part >*
TaskInput::mutable_part() {
  return &part_;
}

// -------------------------------------------------------------------

// TaskOutput

// required string name = 1;
inline bool TaskOutput::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskOutput::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskOutput::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskOutput::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TaskOutput::name() const {
  return *name_;
}
inline void TaskOutput::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskOutput::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskOutput::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskOutput::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* TaskOutput::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskOutput::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string file_format = 2;
inline bool TaskOutput::has_file_format() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskOutput::set_has_file_format() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskOutput::clear_has_file_format() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskOutput::clear_file_format() {
  if (file_format_ != &::google::protobuf::internal::kEmptyString) {
    file_format_->clear();
  }
  clear_has_file_format();
}
inline const ::std::string& TaskOutput::file_format() const {
  return *file_format_;
}
inline void TaskOutput::set_file_format(const ::std::string& value) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(value);
}
inline void TaskOutput::set_file_format(const char* value) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(value);
}
inline void TaskOutput::set_file_format(const char* value, size_t size) {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  file_format_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskOutput::mutable_file_format() {
  set_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    file_format_ = new ::std::string;
  }
  return file_format_;
}
inline ::std::string* TaskOutput::release_file_format() {
  clear_has_file_format();
  if (file_format_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_format_;
    file_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskOutput::set_allocated_file_format(::std::string* file_format) {
  if (file_format_ != &::google::protobuf::internal::kEmptyString) {
    delete file_format_;
  }
  if (file_format) {
    set_has_file_format();
    file_format_ = file_format;
  } else {
    clear_has_file_format();
    file_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string record_format = 3;
inline bool TaskOutput::has_record_format() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TaskOutput::set_has_record_format() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TaskOutput::clear_has_record_format() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TaskOutput::clear_record_format() {
  if (record_format_ != &::google::protobuf::internal::kEmptyString) {
    record_format_->clear();
  }
  clear_has_record_format();
}
inline const ::std::string& TaskOutput::record_format() const {
  return *record_format_;
}
inline void TaskOutput::set_record_format(const ::std::string& value) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(value);
}
inline void TaskOutput::set_record_format(const char* value) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(value);
}
inline void TaskOutput::set_record_format(const char* value, size_t size) {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  record_format_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskOutput::mutable_record_format() {
  set_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    record_format_ = new ::std::string;
  }
  return record_format_;
}
inline ::std::string* TaskOutput::release_record_format() {
  clear_has_record_format();
  if (record_format_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = record_format_;
    record_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskOutput::set_allocated_record_format(::std::string* record_format) {
  if (record_format_ != &::google::protobuf::internal::kEmptyString) {
    delete record_format_;
  }
  if (record_format) {
    set_has_record_format();
    record_format_ = record_format;
  } else {
    clear_has_record_format();
    record_format_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 shards = 4 [default = 0];
inline bool TaskOutput::has_shards() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TaskOutput::set_has_shards() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TaskOutput::clear_has_shards() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TaskOutput::clear_shards() {
  shards_ = 0;
  clear_has_shards();
}
inline ::google::protobuf::int32 TaskOutput::shards() const {
  return shards_;
}
inline void TaskOutput::set_shards(::google::protobuf::int32 value) {
  set_has_shards();
  shards_ = value;
}

// optional string file_base = 5;
inline bool TaskOutput::has_file_base() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TaskOutput::set_has_file_base() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TaskOutput::clear_has_file_base() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TaskOutput::clear_file_base() {
  if (file_base_ != &::google::protobuf::internal::kEmptyString) {
    file_base_->clear();
  }
  clear_has_file_base();
}
inline const ::std::string& TaskOutput::file_base() const {
  return *file_base_;
}
inline void TaskOutput::set_file_base(const ::std::string& value) {
  set_has_file_base();
  if (file_base_ == &::google::protobuf::internal::kEmptyString) {
    file_base_ = new ::std::string;
  }
  file_base_->assign(value);
}
inline void TaskOutput::set_file_base(const char* value) {
  set_has_file_base();
  if (file_base_ == &::google::protobuf::internal::kEmptyString) {
    file_base_ = new ::std::string;
  }
  file_base_->assign(value);
}
inline void TaskOutput::set_file_base(const char* value, size_t size) {
  set_has_file_base();
  if (file_base_ == &::google::protobuf::internal::kEmptyString) {
    file_base_ = new ::std::string;
  }
  file_base_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskOutput::mutable_file_base() {
  set_has_file_base();
  if (file_base_ == &::google::protobuf::internal::kEmptyString) {
    file_base_ = new ::std::string;
  }
  return file_base_;
}
inline ::std::string* TaskOutput::release_file_base() {
  clear_has_file_base();
  if (file_base_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_base_;
    file_base_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskOutput::set_allocated_file_base(::std::string* file_base) {
  if (file_base_ != &::google::protobuf::internal::kEmptyString) {
    delete file_base_;
  }
  if (file_base) {
    set_has_file_base();
    file_base_ = file_base;
  } else {
    clear_has_file_base();
    file_base_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string file_extension = 6;
inline bool TaskOutput::has_file_extension() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TaskOutput::set_has_file_extension() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TaskOutput::clear_has_file_extension() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TaskOutput::clear_file_extension() {
  if (file_extension_ != &::google::protobuf::internal::kEmptyString) {
    file_extension_->clear();
  }
  clear_has_file_extension();
}
inline const ::std::string& TaskOutput::file_extension() const {
  return *file_extension_;
}
inline void TaskOutput::set_file_extension(const ::std::string& value) {
  set_has_file_extension();
  if (file_extension_ == &::google::protobuf::internal::kEmptyString) {
    file_extension_ = new ::std::string;
  }
  file_extension_->assign(value);
}
inline void TaskOutput::set_file_extension(const char* value) {
  set_has_file_extension();
  if (file_extension_ == &::google::protobuf::internal::kEmptyString) {
    file_extension_ = new ::std::string;
  }
  file_extension_->assign(value);
}
inline void TaskOutput::set_file_extension(const char* value, size_t size) {
  set_has_file_extension();
  if (file_extension_ == &::google::protobuf::internal::kEmptyString) {
    file_extension_ = new ::std::string;
  }
  file_extension_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskOutput::mutable_file_extension() {
  set_has_file_extension();
  if (file_extension_ == &::google::protobuf::internal::kEmptyString) {
    file_extension_ = new ::std::string;
  }
  return file_extension_;
}
inline ::std::string* TaskOutput::release_file_extension() {
  clear_has_file_extension();
  if (file_extension_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = file_extension_;
    file_extension_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskOutput::set_allocated_file_extension(::std::string* file_extension) {
  if (file_extension_ != &::google::protobuf::internal::kEmptyString) {
    delete file_extension_;
  }
  if (file_extension) {
    set_has_file_extension();
    file_extension_ = file_extension;
  } else {
    clear_has_file_extension();
    file_extension_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// TaskSpec_Parameter

// required string name = 4;
inline bool TaskSpec_Parameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskSpec_Parameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskSpec_Parameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskSpec_Parameter::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TaskSpec_Parameter::name() const {
  return *name_;
}
inline void TaskSpec_Parameter::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskSpec_Parameter::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void TaskSpec_Parameter::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskSpec_Parameter::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* TaskSpec_Parameter::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskSpec_Parameter::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string value = 5;
inline bool TaskSpec_Parameter::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskSpec_Parameter::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskSpec_Parameter::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskSpec_Parameter::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& TaskSpec_Parameter::value() const {
  return *value_;
}
inline void TaskSpec_Parameter::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void TaskSpec_Parameter::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void TaskSpec_Parameter::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskSpec_Parameter::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* TaskSpec_Parameter::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskSpec_Parameter::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// TaskSpec

// optional string task_name = 1;
inline bool TaskSpec::has_task_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TaskSpec::set_has_task_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TaskSpec::clear_has_task_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TaskSpec::clear_task_name() {
  if (task_name_ != &::google::protobuf::internal::kEmptyString) {
    task_name_->clear();
  }
  clear_has_task_name();
}
inline const ::std::string& TaskSpec::task_name() const {
  return *task_name_;
}
inline void TaskSpec::set_task_name(const ::std::string& value) {
  set_has_task_name();
  if (task_name_ == &::google::protobuf::internal::kEmptyString) {
    task_name_ = new ::std::string;
  }
  task_name_->assign(value);
}
inline void TaskSpec::set_task_name(const char* value) {
  set_has_task_name();
  if (task_name_ == &::google::protobuf::internal::kEmptyString) {
    task_name_ = new ::std::string;
  }
  task_name_->assign(value);
}
inline void TaskSpec::set_task_name(const char* value, size_t size) {
  set_has_task_name();
  if (task_name_ == &::google::protobuf::internal::kEmptyString) {
    task_name_ = new ::std::string;
  }
  task_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskSpec::mutable_task_name() {
  set_has_task_name();
  if (task_name_ == &::google::protobuf::internal::kEmptyString) {
    task_name_ = new ::std::string;
  }
  return task_name_;
}
inline ::std::string* TaskSpec::release_task_name() {
  clear_has_task_name();
  if (task_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = task_name_;
    task_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskSpec::set_allocated_task_name(::std::string* task_name) {
  if (task_name_ != &::google::protobuf::internal::kEmptyString) {
    delete task_name_;
  }
  if (task_name) {
    set_has_task_name();
    task_name_ = task_name;
  } else {
    clear_has_task_name();
    task_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string task_type = 2;
inline bool TaskSpec::has_task_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TaskSpec::set_has_task_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TaskSpec::clear_has_task_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TaskSpec::clear_task_type() {
  if (task_type_ != &::google::protobuf::internal::kEmptyString) {
    task_type_->clear();
  }
  clear_has_task_type();
}
inline const ::std::string& TaskSpec::task_type() const {
  return *task_type_;
}
inline void TaskSpec::set_task_type(const ::std::string& value) {
  set_has_task_type();
  if (task_type_ == &::google::protobuf::internal::kEmptyString) {
    task_type_ = new ::std::string;
  }
  task_type_->assign(value);
}
inline void TaskSpec::set_task_type(const char* value) {
  set_has_task_type();
  if (task_type_ == &::google::protobuf::internal::kEmptyString) {
    task_type_ = new ::std::string;
  }
  task_type_->assign(value);
}
inline void TaskSpec::set_task_type(const char* value, size_t size) {
  set_has_task_type();
  if (task_type_ == &::google::protobuf::internal::kEmptyString) {
    task_type_ = new ::std::string;
  }
  task_type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TaskSpec::mutable_task_type() {
  set_has_task_type();
  if (task_type_ == &::google::protobuf::internal::kEmptyString) {
    task_type_ = new ::std::string;
  }
  return task_type_;
}
inline ::std::string* TaskSpec::release_task_type() {
  clear_has_task_type();
  if (task_type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = task_type_;
    task_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void TaskSpec::set_allocated_task_type(::std::string* task_type) {
  if (task_type_ != &::google::protobuf::internal::kEmptyString) {
    delete task_type_;
  }
  if (task_type) {
    set_has_task_type();
    task_type_ = task_type;
  } else {
    clear_has_task_type();
    task_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated group Parameter = 3 {
inline int TaskSpec::parameter_size() const {
  return parameter_.size();
}
inline void TaskSpec::clear_parameter() {
  parameter_.Clear();
}
inline const ::chrome_lang_id::TaskSpec_Parameter& TaskSpec::parameter(int index) const {
  return parameter_.Get(index);
}
inline ::chrome_lang_id::TaskSpec_Parameter* TaskSpec::mutable_parameter(int index) {
  return parameter_.Mutable(index);
}
inline ::chrome_lang_id::TaskSpec_Parameter* TaskSpec::add_parameter() {
  return parameter_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskSpec_Parameter >&
TaskSpec::parameter() const {
  return parameter_;
}
inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskSpec_Parameter >*
TaskSpec::mutable_parameter() {
  return &parameter_;
}

// repeated .chrome_lang_id.TaskInput input = 6;
inline int TaskSpec::input_size() const {
  return input_.size();
}
inline void TaskSpec::clear_input() {
  input_.Clear();
}
inline const ::chrome_lang_id::TaskInput& TaskSpec::input(int index) const {
  return input_.Get(index);
}
inline ::chrome_lang_id::TaskInput* TaskSpec::mutable_input(int index) {
  return input_.Mutable(index);
}
inline ::chrome_lang_id::TaskInput* TaskSpec::add_input() {
  return input_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput >&
TaskSpec::input() const {
  return input_;
}
inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskInput >*
TaskSpec::mutable_input() {
  return &input_;
}

// repeated .chrome_lang_id.TaskOutput output = 7;
inline int TaskSpec::output_size() const {
  return output_.size();
}
inline void TaskSpec::clear_output() {
  output_.Clear();
}
inline const ::chrome_lang_id::TaskOutput& TaskSpec::output(int index) const {
  return output_.Get(index);
}
inline ::chrome_lang_id::TaskOutput* TaskSpec::mutable_output(int index) {
  return output_.Mutable(index);
}
inline ::chrome_lang_id::TaskOutput* TaskSpec::add_output() {
  return output_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskOutput >&
TaskSpec::output() const {
  return output_;
}
inline ::google::protobuf::RepeatedPtrField< ::chrome_lang_id::TaskOutput >*
TaskSpec::mutable_output() {
  return &output_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace chrome_lang_id

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_task_5fspec_2eproto__INCLUDED
