#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_FFI_CLOSURE_ALLOC 1
#define HAVE_FFI_RAW_CALL 1
#define HAVE_FFI_PREP_RAW_CLOSURE 1
#define HAVE_RAW_API 1
#define HAVE_RB_THREAD_CALL_WITH_GVL 1
#define HAVE_RB_THREAD_CALL_WITHOUT_GVL 1
#define HAVE_FFI_PREP_CIF_VAR 1
#define RUBY_1_9 1
#endif
