default: &default
  adapter: postgresql
  pool: <%= ENV["DB_POOL"] || (if Sidekiq.server? then Sidekiq[:concurrency] else ENV['MAX_THREADS'] end) || 5 %>
  timeout: 5000
  connect_timeout: 15
  encoding: unicode
  sslmode: <%= ENV['DB_SSLMODE'] || "prefer" %>
  application_name: ''

development:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon_development' %>
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
  replica:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon_development' %>
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    replica: true
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DB_NAME'] || 'mastodon_development_queue' %>
    migrations_paths: db/queue_migrate
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon' %>_test<%= ENV['TEST_ENV_NUMBER'] %>
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
  replica:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon' %>_test<%= ENV['TEST_ENV_NUMBER'] %>
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>
    replica: true
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DB_NAME'] || 'mastodon' %>_test<%= ENV['TEST_ENV_NUMBER'] %>
    migrations_paths: db/queue_migrate
    username: <%= ENV['DB_USER'] %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] %>
    port: <%= ENV['DB_PORT'] %>

production:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] || 'mastodon_production' %>
    username: <%= ENV['DB_USER'] || 'mastodon' %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
    prepared_statements: <%= ENV['PREPARED_STATEMENTS'] || 'true' %>
  replica:
    <<: *default
    database: <%= ENV['REPLICA_DB_NAME'] ||ENV['DB_NAME'] || 'mastodon_production' %>
    username: <%= ENV['REPLICA_DB_USER'] ||ENV['DB_USER'] || 'mastodon' %>
    password: <%= (ENV['REPLICA_DB_PASS'] || ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['REPLICA_DB_HOST'] ||ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['REPLICA_DB_PORT'] ||ENV['DB_PORT'] || 5432 %>
    prepared_statements: <%= ENV['PREPARED_STATEMENTS'] || 'true' %>
    replica: true
  queue:
    <<: *default
    database: <%= ENV['QUEUE_DB_NAME'] || 'mastodon_production_queue' %>
    migrations_paths: db/queue_migrate
    username: <%= ENV['DB_USER'] || 'mastodon' %>
    password: <%= (ENV['DB_PASS'] || '').to_json %>
    host: <%= ENV['DB_HOST'] || 'localhost' %>
    port: <%= ENV['DB_PORT'] || 5432 %>
    prepared_statements: <%= ENV['PREPARED_STATEMENTS'] || 'true' %>
