# Note that these settings only apply in `production` even when other
# keys are added here.
production:
  delivery_method: <%= ENV.fetch('SMTP_DELIVERY_METHOD', 'smtp') %>
  from_address: <%= ENV.fetch('SMTP_FROM_ADDRESS', 'notifications@localhost')&.to_json %>
  reply_to: <%= ENV.fetch('SMTP_REPLY_TO', nil)&.to_json %>
  return_path: <%= ENV.fetch('SMTP_RETURN_PATH', nil)&.to_json %>
  smtp_settings:
    port: <%= ENV.fetch('SMTP_PORT', nil) %>
    address: <%= ENV.fetch('SMTP_SERVER', nil)&.to_json %>
    user_name: <%= ENV.fetch('SMTP_LOGIN', nil)&.to_json %>
    password: <%= ENV.fetch('SMTP_PASSWORD', nil)&.to_json %>
    domain: <%= ENV.fetch('SMTP_DOMAIN', ENV.fetch('LOCAL_DOMAIN', nil)) %>
    authentication: <%= ENV.fetch('SMTP_AUTH_METHOD', 'plain') %>
    ca_file: <%= ENV.fetch('SMTP_CA_FILE', '/etc/ssl/certs/ca-certificates.crt') %>
    openssl_verify_mode: <%= ENV.fetch('SMTP_OPENSSL_VERIFY_MODE', nil) %>
    enable_starttls: <%= ENV.fetch('SMTP_ENABLE_STARTTLS', nil) %>
    enable_starttls_auto: <%= ENV.fetch('SMTP_ENABLE_STARTTLS_AUTO', true) != 'false' %>
    tls: <%= ENV.fetch('SMTP_TLS', false) == 'true' ? true : nil %>
    ssl: <%= ENV.fetch('SMTP_SSL', false) == 'true' ? true : nil %>
    read_timeout: 20
  bulk_mail:
    smtp_settings:
      port: <%= ENV.fetch('BULK_SMTP_PORT', nil) %>
      address: <%= ENV.fetch('BULK_SMTP_SERVER', nil)&.to_json %>
      user_name: <%= ENV.fetch('BULK_SMTP_LOGIN', nil)&.to_json %>
      password: <%= ENV.fetch('BULK_SMTP_PASSWORD', nil)&.to_json %>
      domain: <%= ENV.fetch('BULK_SMTP_DOMAIN', ENV.fetch('LOCAL_DOMAIN', nil)) %>
      authentication: <%= ENV.fetch('BULK_SMTP_AUTH_METHOD', 'plain') %>
      ca_file: <%= ENV.fetch('BULK_SMTP_CA_FILE', '/etc/ssl/certs/ca-certificates.crt') %>
      openssl_verify_mode: <%= ENV.fetch('BULK_SMTP_OPENSSL_VERIFY_MODE', nil) %>
      enable_starttls: <%= ENV.fetch('BULK_SMTP_ENABLE_STARTTLS', nil) %>
      enable_starttls_auto: <%= ENV.fetch('BULK_SMTP_ENABLE_STARTTLS_AUTO', true) != 'false' %>
      tls: <%= ENV.fetch('BULK_SMTP_TLS', false) == 'true' ? true : nil %>
      ssl: <%= ENV.fetch('BULK_SMTP_SSL', false) == 'true' ? true : nil %>
      read_timeout: 20
