shared:
  apps:
    f-droid:
      id: org.joinmastodon.android
      url: https://f-droid.org/en/packages/org.joinmastodon.android/
    itunes:
      id: id1571998974
      url: https://apps.apple.com/us/app/mastodon/id1571998974
    play:
      id: org.joinmastodon.android
      url: https://play.google.com/store/apps/details?id=org.joinmastodon.android
