shared:
  deepl:
    api_key: <%= ENV.fetch('DEEPL_API_KEY', nil) %>
    plan: <%= ENV.fetch('DEEPL_PLAN', 'free') %>
  libre_translate:
    api_key: <%= ENV.fetch('LIBRE_TRANSLATE_API_KEY', nil) %>
    endpoint: <%= ENV.fetch('LIBRE_TRANSLATE_ENDPOINT', nil) %>
  openai:
    api_key: <%= ENV.fetch('OPENAI_API_KEY', nil) %>
    endpoint: <%= ENV.fetch('OPENAI_ENDPOINT', nil) %>
    model: <%= ENV.fetch('OPENAI_MODEL', nil) %>
