# Main configuration for Vite integration inside Rails
# see lib/vite/config.rb for more info
#
# All values need to match Vite's configuration in vite.config.mts
shared:
  cache_dir: 'node_modules/.vite'

development:
  host: 'localhost'
  port: 3036
  https: false
  base_path: '/packs-dev/'
  manifest_path: 'public/packs-dev/.vite/manifest.json'
  manifest_assets_path: 'public/packs-dev/.vite/manifest-assets.json'
  auto_build: true
  build_command: 'yarn build:development'
  tag_strategies: ['dev_server', 'manifest']
  out_dir: 'public/packs-dev'

test:
  base_path: '/packs/'
  manifest_path: 'public/packs/.vite/manifest.json'
  manifest_assets_path: 'public/packs/.vite/manifest-assets.json'
  auto_build: true
  build_command: 'yarn build:production'
  tag_strategies: ['manifest']
  out_dir: 'public/packs'

production:
  base_path: '/packs/'
  manifest_path: 'public/packs/.vite/manifest.json'
  manifest_assets_path: 'public/packs/.vite/manifest-assets.json'
  auto_build: false
  build_command: 'yarn build:production'
  tag_strategies: ['manifest']
  out_dir: 'public/packs'
