/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/accounts/{account_id}": {
    get: {
      parameters: {
        path: {
          /** account id */
          account_id: string;
        };
      };
      responses: {
        /** account profile */
        200: {
          content: {
            "application/json": components["schemas"]["account"];
          };
        };
        /** forbidden */
        403: {
          content: {
            "application/json": components["schemas"]["error"];
          };
        };
        /** not found */
        404: {
          content: {
            "application/json": components["schemas"]["error"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    account: {
      id: string;
      username: string;
      acct: string;
      display_name: string;
      locked: boolean;
      bot: boolean;
      /** Format: datetime */
      created_at: string;
      note: string;
      url: string;
      avatar: string;
      avatar_static: string;
      header: string;
      header_static: string;
      followers_count: number;
      following_count: number;
      statuses_count: number;
      last_status_at: components["schemas"]["account_last_status_at"];
      fields: components["schemas"]["account_field"][];
      emojis: components["schemas"]["custom_emoji"][];
      discoverable: boolean;
      group: boolean;
      noindex: boolean;
      roles: components["schemas"]["account_role"][];
    };
    error: {
      error: string;
    };
    /** @enum {string|null} */
    null: null | null;
    account_field: {
      name: string;
      value: string;
      verified_at: components["schemas"]["account_last_status_at"];
    };
    custom_emoji: {
      shortcode: string;
      url: string;
      static_url: string;
      visible_in_picker: boolean;
      category: string;
    };
    account_role: {
      color: string;
      id: string;
      name: string;
    };
    account_last_status_at: string | components["schemas"]["null"];
  };
}

export interface operations {}

export interface external {}
