name: Ruby Linting
on:
  merge_group:
  push:
    branches:
      - 'main'
      - 'stable-*'
    paths:
      - 'Gemfile*'
      - '.rubocop*.yml'
      - '.ruby-version'
      - 'bin/rubocop'
      - '**/*.rb'
      - '**/*.rake'
      - '.github/workflows/lint-ruby.yml'

  pull_request:
    paths:
      - 'Gemfile*'
      - '.rubocop*.yml'
      - '.ruby-version'
      - 'bin/rubocop'
      - '**/*.rb'
      - '**/*.rake'
      - '.github/workflows/lint-ruby.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      BUNDLE_ONLY: development

    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bin/rubocop --format github

      - name: Run brakeman
        if: always() # Run both checks, even if the first failed
        run: bin/brakeman
